### ISSUE TITLE
MacOS M1: could not find audio recording device

### ISSUE THREAD

**Issue by fetsorn** [rbrisita/codio-sui#107]
I get the following error on Visual Studio Code on MacOS Monterey 12.1, MacBook Air M1 2020 - "Codio could not find an audio recording device".
There's an ffmpeg in PATH, version 4.4.1, built with clang version 11.1.0
Do you support arm64 macs? If not, could you hint at what I need to do to add support?

**Comment by rbrisita** [comment]
This fork does support Linux, OS X (Tested on High Sierra), and Windows. I will update with a beta release version and instructions to install soon and update this issue.

**Comment by rbrisita** [comment]
Also, if you could tell me what the output is when you run:

`ffmpeg -hide_banner -nostats -f avfoundation -list_devices true -i ""`

That would help. I am guessing that the format (avfoundation) has changed.

**Comment by fetsorn** [comment]
Ah, that was it, my ffmpeg did not support avfoundation.
I installed another version of ffmpeg and codio-sui now works well, and so does the original codio.
The .vsix you've published was installed just as well as the one I'd previously built myself.
Thanks for a quick reply, closing.

**Comment by rbrisita** [comment]
I'm curious as to what it was using instead, as I only know OS X to support 'avfoundation'. What version did you install previously?

**Comment by fetsorn** [comment]
The one packaged with nix
https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=ffmpeg

**Comment by rbrisita** [comment]
Ah, interesting tool. Thanks for introducing it to me.
